(load "./4.1")

(define (eval exp env)
  (cond ((self-evaluating? exp) exp)
        ((variable? exp) (lookup-variable-value exp env))
        ((quoted? exp) (text-of-quotation exp))
        ((assignment? exp) (eval-assignment exp env))
        ((definition? exp) (eval-definition exp env))
        ((if? exp) (eval-if exp env))
        ((lambda? exp)
         (make-procedure (lambda-parameters exp)
                         (lambda-body exp)
                         env))
        ((begin? exp)
         (eval-sequence (begin-actions exp) env))
        ((cond? exp) (eval (cond->if exp) env))
        ((let? exp) (print (let->combination exp)) (eval (let->combination exp) env))
        ((application? exp)
         (apply (eval (operator exp) env)
                (list-of-values (operands exp) env)))
        (else
          (error "Unknown expression type -- EVAL" exp))))

(define (let? exp) (tagged-list? exp 'let))

(define (make-definition variables body)
  (list 'define variables body))

(define (let->combination exp)
  (if (variable? (cadr exp))
    (let ((operator (cadr exp))
          (operands (map car (caddr exp)))
          (inits (map cadr (caddr exp)))
          (body (cdddr exp)))
      (make-begin
        (list (make-definition operator (make-lambda operands body))
              (cons operator inits))))
    (let ((params (map car (cadr exp)))
          (inits (map cadr (cadr exp)))
          (body (cddr exp)))
      (cons (make-lambda params body) inits))))

(driver-loop)
; (begin (define (fib n) (let fib-iter ((a 1) (b 0) (count n)) (if (= count 0) b (fib-iter (+ a b) a (- count 1))))) (fib 10))

